Feat/added menu item details activity
blackspyek/food-ordering-app pull request #14
Opened 2024-10-18 16:48 UTC by DFraczek

# Pull Request: Menu Item Detail Activity Implementation

## Overview

This pull request implements the **Menu Item Detail Activity** in our Android application. This activity displays detailed information about a selected menu item, including an image, name, description, and an "Add to Basket" button.

## Changes Made

- **Created `MenuItemDetailActivity`**:
  - This activity is responsible for displaying the details of a selected menu item.
  - Utilizes a toolbar for navigation and back functionality.
  
- **User Interface**:
  - Added an `ImageView` to display the dish's image using Glide for image loading.
  - Added `TextView`s for displaying the dish name and description.
  - Added a `Button` labeled "Add to basket" for adding the item to the user's basket.

- **Navigation**:
  - Implemented navigation from the menu to the detail activity.
  - Added back navigation functionality using the toolbar.

- **Data Handling**:
  - Retrieved the `MenuItem` object passed via intent to populate the UI elements.
  - Implemented a click listener for the "Add to Basket" button, logging the action (to be expanded with actual basket logic in future updates).

## Screenshots

![image](https://github.com/user-attachments/assets/104fa051-8021-43d9-9a13-29dc2cab80cf)

## Future Work

- Implement the functionality to add the selected menu item to the user's basket.

2024-10-18 16:50 UTC, DFraczek commented
![image](https://github.com/user-attachments/assets/8a11b410-cfe9-476c-b00b-7afca4f18085)

2024-10-18 17:47 UTC, blackspyek requested changes

2024-10-18 17:47 UTC, blackspyek commented on Android/app/src/main/java/com/example/android/activities/MenuActivity.java
> +        menuItemAdapter = new MenuItemAdapter(null, "", new MenuItemAdapter.OnItemClickListener() {
extract method

2024-10-19 07:51 UTC, blackspyek requested changes

2024-10-19 07:51 UTC, blackspyek commented on Android/app/src/main/java/com/example/android/activities/MenuItemDetailActivity.java
> +        ImageView itemImage = findViewById(R.id.itemImage);
This imo should be extracted cause its field init

2024-10-19 07:51 UTC, blackspyek commented on Android/app/src/main/java/com/example/android/activities/MenuItemDetailActivity.java
> +        addToBasketButton.setOnClickListener(new View.OnClickListener() {
Extract

2024-10-19 07:51 UTC, blackspyek commented on Android/app/src/main/java/com/example/android/models/MenuItem.java
> +    public String getDescription() {
When you are doing getters and setters use annotations @Gettet and @Setter also for args and noargs constructor

2024-10-19 10:06 UTC, blackspyek approved these changes
LGTM

2024-10-19 10:07 UTC, merged