feat/register with backend
blackspyek/food-ordering-app pull request #7
Opened 2024-10-13 13:25 UTC by zo02

### Pull Request: Feat/Register with Backend

## Overview
This pull request implements the registration functionality for the frontend to communicate with the backend API. Users can now register using the designated endpoints, enhancing the overall user experience by integrating backend services.

## Changes Made

**Frontend Integration with Backend:**
- Updated the registration view to utilize backend endpoints for user registration.
- Implemented user input validation in the registration form, ensuring all fields are filled out correctly before submission.
- Included a ChoiceBox for user role selection, allowing users to specify their role during registration.

**Login Controller Enhancements:**
- Modified the login controller to facilitate navigation to the registration form.
- This temporary setup will eventually be replaced to direct users to the appropriate view (manager or employee) based on their role after successful login.

## Additional Notes
- The current implementation of opening the registration form upon login is temporary and intended for testing purposes. Future updates will modify this behavior to route users based on their assigned roles.
- Please review the changes made to the registration process and let me know if there are any suggestions or further modifications required!

2024-10-13 13:46 UTC, blackspyek requested changes
Overall, this implementation is solid (in several cases need to be repaired), but I recommend refactoring it to enhance clarity and adherence to clean code principles. This way, a new reader will be able to understand the method's purpose at a glance without needing to delve into the logic. Clearer method names, consistent formatting, and well-structured comments could significantly improve readability (these which i commented at)

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/controllers/LoginViewController.java
> +            FXMLLoader loader = new FXMLLoader(Main.class.getResource("register-view.fxml"));
Extract it to a new method because its too long to read'

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/controllers/LoginViewController.java
> +            Stage loginStage = (Stage) loginMessageLabel.getScene().getWindow();
I would make here another method to close that stage in one line

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/dto/RegisterUserDto.java
> +        this.role = role;
So this isnt matching with backend

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/dto/RegisterUserDto.java
> +        return username;
Instead of using manual getters and setters use lombok getters and setters

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/RegisterViewController.java
> +    private String[] roles = {"ROLE_USER", "ROLE_MANAGER", "ROLE_EMPLOYEE"};
I would use global enum somewhere instead

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/RegisterViewController.java
> +        RegisterUserDto registerUserDto = new RegisterUserDto(username, password, role);
and that's what i've told you on dc, we doesnt provide role in register

2024-10-13 13:46 UTC, blackspyek commented on gui/Test/src/main/java/sample/test/RegisterViewController.java
> +            if (jwtToken != null && !jwtToken.isBlank()) {
that's okay i guess, maybe a little bit too long to read in one method, you could try extract something
also keep in mind that a user with ROLE_MANAGER will only be able to add new Employees

2024-10-13 18:29 UTC, zo02 commented
I cleaned the code and fixed the RegisterUserDto as requested. For now i deleted the roles from this Controller. They will be added to a different controller in the future.

2024-10-14 09:01 UTC, blackspyek approved these changes
## Don't forget to squash
![image](https://github.com/user-attachments/assets/5166ad4f-e199-487c-87dd-fa70a07ac383)

2024-10-14 10:25 UTC, merged